spring.application.name=react_semi_back
#server port
server.port=8080

#oracle settings
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@1.223.77.178:15211/XEPDB1
spring.datasource.username=TEAM3_DB
spring.datasource.password=3333

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#swagger settings
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha